using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json.Linq;

namespace Lelware.Sdk.Editor
{
    /// <summary>
    ///     Turns the portal's global OpenAPI 3 document (served by <c>api/sdk/OpenApi</c>) into a
    ///     single C# source file: one <c>[Serializable]</c> DTO per <c>components.schemas</c> entry
    ///     and one extension method on <see cref="LelwareClient" /> per operation. This is the
    ///     "everything except Authentication is generated" half — Login stays hand-written because
    ///     its dual-body response and bootstrap nature don't fit a generated call.
    ///
    ///     Deliberately a SMALL, targeted OpenAPI reader (not a general-purpose one), but general
    ///     enough for every path this portal emits: any number of path parameters anywhere in the
    ///     route (e.g. <c>/api/maps/tiles/{x}/{y}/{z}.vector</c>), query
    ///     parameters, a JSON request body, and a JSON / binary / empty response. Anything it can't
    ///     classify degrades to <c>object</c> rather than failing.
    ///
    ///     The full request path is built by the generated method itself, substituting each
    ///     <c>{param}</c>: the project-id token (<c>{projectId}</c>/<c>{pid}</c>) is filled from
    ///     <c>client.ProjectId</c> (never a method argument, so one SDK serves every project),
    ///     every other path param becomes a method argument. Calls go through the path-based
    ///     transport on <see cref="LelwareClient" />, inheriting the token/Is-Client headers and
    ///     the exception-free <see cref="LelwareResult{T}" /> contract.
    /// </summary>
    public static class OpenApiCodeGenerator
    {
        public static string Generate(string openApiJson)
        {
            if (string.IsNullOrWhiteSpace(openApiJson))
            {
                throw new ArgumentException("OpenAPI document is empty.", nameof(openApiJson));
            }

            JObject doc = JObject.Parse(openApiJson);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated from the portal's OpenAPI document by the Lelware SDK generator.");
            sb.AppendLine("//     DO NOT EDIT BY HAND — re-run Tools > Lelware > Generate SDK from Portal.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine();
            sb.AppendLine("namespace Lelware.Sdk.Generated");
            sb.AppendLine("{");

            EmitSchemas(sb, doc);
            EmitOperations(sb, doc);

            sb.AppendLine("}");
            return sb.ToString();
        }

        // --- components.schemas -> DTO classes --------------------------------

        private static void EmitSchemas(StringBuilder sb, JObject doc)
        {
            var schemas = doc["components"]?["schemas"] as JObject;
            if (schemas == null)
            {
                return;
            }

            foreach (var prop in schemas.Properties())
            {
                var name = SanitizeType(prop.Name);
                var schema = prop.Value as JObject;

                sb.AppendLine("    [Serializable]");
                sb.AppendLine($"    public partial class {name}");
                sb.AppendLine("    {");

                var properties = schema?["properties"] as JObject;
                if (properties != null)
                {
                    foreach (var field in properties.Properties())
                    {
                        var wire = field.Name;
                        var member = SanitizeMember(wire);
                        var type = ResolveType(field.Value as JObject);

                        // Keep the wire name explicit whenever the C# member had to be sanitised,
                        // so (de)serialization still round-trips the original JSON key.
                        if (member != wire)
                        {
                            sb.AppendLine($"        [JsonProperty(\"{Escape(wire)}\")]");
                        }

                        sb.AppendLine($"        public {type} {member};");
                    }
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        // --- paths -> extension methods ---------------------------------------

        private static void EmitOperations(StringBuilder sb, JObject doc)
        {
            sb.AppendLine("    /// <summary>Generated typed calls, one per OpenAPI operation.</summary>");
            sb.AppendLine("    public static class GeneratedApi");
            sb.AppendLine("    {");

            var used = new HashSet<string>();
            var paths = doc["paths"] as JObject;
            if (paths != null)
            {
                foreach (var pathProp in paths.Properties())
                {
                    var pathItem = pathProp.Value as JObject;
                    if (pathItem == null)
                    {
                        continue;
                    }

                    foreach (var verbProp in pathItem.Properties())
                    {
                        var verb = verbProp.Name.ToLowerInvariant();
                        if (verb != "get" && verb != "post" && verb != "put" && verb != "delete")
                        {
                            continue; // skip "parameters", "summary", etc.
                        }

                        EmitMethod(sb, pathProp.Name, verb, verbProp.Value as JObject, used);
                    }
                }
            }

            EmitQueryHelper(sb);

            sb.AppendLine("    }");
        }

        private static void EmitMethod(StringBuilder sb, string path, string verb, JObject op, HashSet<string> used)
        {
            if (op == null)
            {
                return;
            }

            var segments = path.Trim('/').Split('/');
            if (segments.Length < 2 || !segments[0].Equals("api", StringComparison.OrdinalIgnoreCase))
            {
                return; // not an /api/... path we know how to call.
            }

            // Collect declared parameter types up front: path params feed URL substitution,
            // query params become trailing method args.
            var pathParamTypes = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            var queryParams = new List<(string member, string wire, string type)>();
            foreach (var p in (op["parameters"] as JArray) ?? new JArray())
            {
                var loc = p["in"]?.ToString();
                var pname = p["name"]?.ToString();
                if (string.IsNullOrEmpty(pname))
                {
                    continue;
                }

                if (loc == "path")
                {
                    pathParamTypes[pname] = ResolveType(p["schema"] as JObject);
                }
                else if (loc == "query")
                {
                    queryParams.Add((SanitizeMember(pname), pname, ResolveType(p["schema"] as JObject)));
                }
            }

            // Build the path expression (with substitutions) and the ordered path-param args.
            var pathArgs = new List<(string member, string type)>();
            var pathExpr = BuildPathExpression(path, pathParamTypes, pathArgs);

            // Method name: prefer operationId, else derive from the route's literal segments.
            var baseName = op["operationId"]?.ToString();
            if (string.IsNullOrEmpty(baseName))
            {
                baseName = DeriveName(segments, verb);
            }

            var methodName = Unique(used, SanitizeType(baseName)) + "Async";

            var bodyType = ResolveBodyType(op);
            var kind = ClassifyResponse(op, out var responseType); // "json" | "binary" | "none"

            // Signature: path args, then body, then query args, then ct.
            var sig = new List<string> { "this global::Lelware.Sdk.LelwareClient client" };
            foreach (var pa in pathArgs)
            {
                sig.Add(pa.type + " " + pa.member);
            }

            if (bodyType != null)
            {
                sig.Add(bodyType + " body");
            }

            foreach (var q in queryParams)
            {
                sig.Add(q.type + " " + q.member);
            }

            sig.Add("CancellationToken ct = default");

            string returnType;
            switch (kind)
            {
                case "json":
                    returnType = $"global::Lelware.Sdk.LelwareResult<{responseType}>";
                    break;
                case "binary":
                    returnType = "global::Lelware.Sdk.LelwareResult<byte[]>";
                    break;
                default:
                    returnType = "global::Lelware.Sdk.LelwareResult";
                    break;
            }

            var summary = op["summary"]?.ToString() ?? $"{verb.ToUpperInvariant()} {path}";
            sb.AppendLine($"        /// <summary>{Escape(summary)}</summary>");
            sb.AppendLine($"        public static Task<{returnType}> {methodName}({string.Join(", ", sig)})");
            sb.AppendLine("        {");
            sb.AppendLine($"            var __path = {pathExpr};");

            if (queryParams.Count > 0)
            {
                sb.AppendLine("            var __q = new Dictionary<string, string>();");
                foreach (var q in queryParams)
                {
                    sb.AppendLine(
                        $"            __q[\"{Escape(q.wire)}\"] = Convert.ToString({q.member}, CultureInfo.InvariantCulture);");
                }

                sb.AppendLine("            __path += BuildQuery(__q);");
            }

            var bodyExpr = bodyType != null ? "JsonConvert.SerializeObject(body)" : "null";
            var verbLiteral = verb.ToUpperInvariant();

            switch (kind)
            {
                case "json":
                    sb.AppendLine(
                        $"            return client.SendPathAsync<{responseType}>(\"{verbLiteral}\", __path, {bodyExpr}, ct);");
                    break;
                case "binary":
                    sb.AppendLine(
                        $"            return client.SendBytesAsync(\"{verbLiteral}\", __path, {bodyExpr}, ct);");
                    break;
                default:
                    sb.AppendLine(
                        $"            return client.SendPathAsync(\"{verbLiteral}\", __path, {bodyExpr}, ct);");
                    break;
            }

            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // Builds a C# expression that assembles the request path, substituting every {param}:
        //   • {projectId}/{pid} -> client.ProjectId (URL-encoded), never a method arg;
        //   • any other {param}  -> a method arg (added to pathArgs), URL-encoded.
        // A param may sit inside a segment with a literal suffix (e.g. "{z}.vector"), so we
        // substitute on the raw string, not per whole segment.
        private static string BuildPathExpression(string path, Dictionary<string, string> pathParamTypes,
            List<(string member, string type)> pathArgs)
        {
            var parts = new List<string>();
            var literal = new StringBuilder();
            var i = 0;
            while (i < path.Length)
            {
                var c = path[i];
                if (c == '{')
                {
                    var end = path.IndexOf('}', i);
                    if (end < 0)
                    {
                        literal.Append(c); // unbalanced — treat as literal.
                        i++;
                        continue;
                    }

                    // Flush pending literal text.
                    if (literal.Length > 0)
                    {
                        parts.Add($"\"{Escape(literal.ToString())}\"");
                        literal.Clear();
                    }

                    var token = path.Substring(i + 1, end - i - 1);
                    if (IsProjectIdParam(token))
                    {
                        parts.Add("System.Uri.EscapeDataString(client.ProjectId ?? string.Empty)");
                    }
                    else
                    {
                        var member = SanitizeMember(token);
                        var type = pathParamTypes.TryGetValue(token, out var t) ? t : "string";
                        pathArgs.Add((member, type));
                        parts.Add(
                            $"System.Uri.EscapeDataString(System.Convert.ToString({member}, System.Globalization.CultureInfo.InvariantCulture))");
                    }

                    i = end + 1;
                }
                else
                {
                    literal.Append(c);
                    i++;
                }
            }

            if (literal.Length > 0)
            {
                parts.Add($"\"{Escape(literal.ToString())}\"");
            }

            return parts.Count == 0 ? "\"\"" : string.Join(" + ", parts);
        }

        private static bool IsProjectIdParam(string token)
        {
            return token.Equals("projectId", StringComparison.OrdinalIgnoreCase) ||
                   token.Equals("pid", StringComparison.OrdinalIgnoreCase);
        }

        // Derive a method name from the route's literal text (params stripped). PascalCasing
        // happens in SanitizeType, so e.g. "/api/{projectId}/GetSettings/{dataKey}" -> "GetSettings".
        //
        // For a project-DEDICATED endpoint (its first segment after "api" is a literal — a module's
        // own project id — rather than the generic {projectId}/{pid} token) the HTTP verb is
        // inserted right after that project segment, BEFORE the rest of the path. This disambiguates
        // PUT/POST/DELETE on the same resource — which strip to the same literal name and would
        // otherwise get ugly numeric suffixes (Superlikes2/3) — into readable distinct names, e.g.
        // DELETE /api/pixivfe/v2/library/superlikes/{id} -> "PixivfeDeleteV2LibrarySuperlikes".
        //
        // The generic, {projectId}-templated core endpoints are left as-is (verb NOT inserted):
        // their action names already read with the verb baked in (GetSettings, SetPlayerData), so a
        // prefix would just double it up (GetGetSettings).
        private static string DeriveName(string[] segments, string verb)
        {
            // "Dedicated" = first post-"api" segment is a literal, not the project-id token.
            var dedicated = segments.Length >= 2 && !IsProjectIdParam(segments[1].Trim('{', '}'));

            var sb = new StringBuilder();
            for (var s = 1; s < segments.Length; s++) // skip "api"
            {
                sb.Append('/').Append(StripTokens(segments[s]));

                // Slot the verb in immediately after the project segment.
                if (dedicated && s == 1)
                {
                    sb.Append('/').Append(verb);
                }
            }

            return sb.ToString();
        }

        private static string StripTokens(string segment)
        {
            var sb = new StringBuilder(segment.Length);
            var depth = 0;
            foreach (var c in segment)
            {
                if (c == '{')
                {
                    depth++;
                }
                else if (c == '}')
                {
                    if (depth > 0)
                    {
                        depth--;
                    }
                }
                else if (depth == 0)
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }

        // --- schema -> C# type resolution -------------------------------------

        // Classifies the 200 response: "json" (typed via the JSON schema), "binary" (any other
        // media type -> byte[]), or "none" (no content -> bodyless result).
        private static string ClassifyResponse(JObject op, out string type)
        {
            type = "object";
            var content = op?["responses"]?["200"]?["content"] as JObject;
            if (content == null)
            {
                return "none";
            }

            var json = content["application/json"] as JObject;
            if (json != null)
            {
                type = ResolveType(json["schema"] as JObject);
                return "json";
            }

            return "binary"; // octet-stream / protobuf / image / etc.
        }

        private static string ResolveBodyType(JObject op)
        {
            var schema = op?["requestBody"]?["content"]?["application/json"]?["schema"] as JObject;
            return schema == null ? null : ResolveType(schema);
        }

        // Maps an OpenAPI schema node to a C# type string, degrading to "object" when unsure.
        private static string ResolveType(JObject schema)
        {
            if (schema == null)
            {
                return "object";
            }

            var reference = schema["$ref"]?.ToString();
            if (!string.IsNullOrEmpty(reference))
            {
                return SanitizeType(reference.Substring(reference.LastIndexOf('/') + 1));
            }

            var type = schema["type"]?.ToString();
            var format = schema["format"]?.ToString();
            var nullable = schema["nullable"]?.Type == JTokenType.Boolean && schema["nullable"].Value<bool>();

            switch (type)
            {
                case "array":
                    return $"List<{ResolveType(schema["items"] as JObject)}>";
                case "string":
                    return "string";
                case "integer":
                    return (format == "int64" ? "long" : "int") + (nullable ? "?" : "");
                case "number":
                    return (format == "float" ? "float" : "double") + (nullable ? "?" : "");
                case "boolean":
                    return "bool" + (nullable ? "?" : "");
                default:
                    // "object" with no $ref (free-form / anonymous) or unknown -> untyped.
                    return "object";
            }
        }

        // --- emitted query helper ---------------------------------------------

        private static void EmitQueryHelper(StringBuilder sb)
        {
            sb.AppendLine("        // Builds a '?a=b&c=d' query string with URL-encoded keys/values.");
            sb.AppendLine("        private static string BuildQuery(Dictionary<string, string> q)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (q == null || q.Count == 0) return string.Empty;");
            sb.AppendLine("            var sb = new StringBuilder(\"?\");");
            sb.AppendLine("            var first = true;");
            sb.AppendLine("            foreach (var kv in q)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!first) sb.Append('&');");
            sb.AppendLine("                first = false;");
            sb.AppendLine("                sb.Append(System.Uri.EscapeDataString(kv.Key)).Append('=')");
            sb.AppendLine("                  .Append(System.Uri.EscapeDataString(kv.Value ?? string.Empty));");
            sb.AppendLine("            }");
            sb.AppendLine("            return sb.ToString();");
            sb.AppendLine("        }");
        }

        // --- identifier helpers ------------------------------------------------

        private static string Unique(HashSet<string> used, string name)
        {
            var candidate = name;
            var i = 2;
            while (!used.Add(candidate))
            {
                candidate = name + i++;
            }

            return candidate;
        }

        private static readonly HashSet<string> Keywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
            "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
            "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
            "void", "volatile", "while"
        };

        // Type/method identifier: PascalCase across separators (so "Script_my_route" ->
        // "ScriptMyRoute"), strip illegal chars, prefix if it would start with a digit.
        private static string SanitizeType(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return "Type";
            }

            var sb = new StringBuilder(raw.Length);
            var upperNext = true;
            foreach (var c in raw)
            {
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(upperNext ? char.ToUpperInvariant(c) : c);
                    upperNext = false;
                }
                else
                {
                    upperNext = true; // separator: drop it, capitalise whatever comes next.
                }
            }

            if (sb.Length == 0)
            {
                return "Type";
            }

            var ident = sb.ToString();
            return char.IsDigit(ident[0]) ? "_" + ident : ident;
        }

        // Field/parameter identifier: keep casing, escape keywords with '@', fix leading digit.
        private static string SanitizeMember(string raw)
        {
            var ident = Clean(raw);
            if (ident.Length == 0)
            {
                return "_field";
            }

            if (char.IsDigit(ident[0]))
            {
                ident = "_" + ident;
            }

            return Keywords.Contains(ident) ? "@" + ident : ident;
        }

        private static string Clean(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return "";
            }

            var sb = new StringBuilder(raw.Length);
            foreach (var c in raw)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }

        private static string Escape(string s) => (s ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
