using System;
using System.Collections.Generic;
using System.Text;

namespace Lelware.Sdk.Editor
{
    /// <summary>
    ///     Pure code-generation core: turns an <see cref="SdkSchema" /> into a single C# source
    ///     string. Kept free of any UnityEditor dependency so it can be unit-tested or driven
    ///     from a standalone tool — the Editor menu (<see cref="SdkGeneratorMenu" />) is just a
    ///     thin shell around <see cref="Generate" />.
    ///
    ///     Output lives in namespace <c>Lelware.Sdk.Generated</c>:
    ///       • one <c>[Serializable]</c> class per declared type and per inline request/response
    ///         shape;
    ///       • one extension method <c>{Name}Async</c> per endpoint on <see cref="LelwareClient" />
    ///         that delegates to the generic call surface with the right types and route.
    ///     Everything is <c>partial</c> so you can hand-extend a generated class in a sibling
    ///     file without it being clobbered on the next regenerate.
    /// </summary>
    public static class SdkCodeGenerator
    {
        public static string Generate(SdkSchema schema)
        {
            if (schema == null)
            {
                throw new ArgumentNullException(nameof(schema));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by the Lelware SDK schema generator. DO NOT EDIT BY HAND.");
            sb.AppendLine("//     Re-run Tools > Lelware > Generate SDK after editing the schema manifest.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine();
            sb.AppendLine("namespace Lelware.Sdk.Generated");
            sb.AppendLine("{");

            // 1. Reusable named types.
            if (schema.Types != null)
            {
                foreach (var type in schema.Types)
                {
                    EmitClass(sb, type.Name, type.Fields, indent: 1);
                }
            }

            // 2. Inline request/response classes for endpoints that declare fields.
            if (schema.Endpoints != null)
            {
                foreach (var ep in schema.Endpoints)
                {
                    if (ep.Request?.Fields != null && ep.Request.Fields.Count > 0)
                    {
                        EmitClass(sb, ep.Name + "Request", ep.Request.Fields, indent: 1);
                    }

                    if (ep.Response?.Fields != null && ep.Response.Fields.Count > 0)
                    {
                        EmitClass(sb, ep.Name + "Response", ep.Response.Fields, indent: 1);
                    }
                }
            }

            // 3. Extension methods — one typed call per endpoint.
            sb.AppendLine("    /// <summary>Generated typed call methods, one per schema endpoint.</summary>");
            sb.AppendLine("    public static class GeneratedEndpoints");
            sb.AppendLine("    {");
            if (schema.Endpoints != null)
            {
                foreach (var ep in schema.Endpoints)
                {
                    EmitEndpointMethod(sb, ep);
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void EmitClass(StringBuilder sb, string name, List<FieldDef> fields, int indent)
        {
            var pad = new string(' ', indent * 4);
            sb.Append(pad).AppendLine("[Serializable]");
            sb.Append(pad).Append("public partial class ").AppendLine(name);
            sb.Append(pad).AppendLine("{");
            if (fields != null)
            {
                foreach (var f in fields)
                {
                    if (!string.IsNullOrEmpty(f.Json) && f.Json != f.Name)
                    {
                        sb.Append(pad).Append("    [JsonProperty(\"").Append(f.Json).AppendLine("\")]");
                    }

                    sb.Append(pad).Append("    public ").Append(f.Type).Append(' ').Append(f.Name).AppendLine(";");
                }
            }

            sb.Append(pad).AppendLine("}");
            sb.AppendLine();
        }

        private static void EmitEndpointMethod(StringBuilder sb, EndpointDef ep)
        {
            var responseType = ResolveType(ep.Response, ep.Name + "Response", fallback: "object");
            var requestType = ResolveType(ep.Request, ep.Name + "Request", fallback: null);
            var isGet = string.Equals(ep.Method, "GET", StringComparison.OrdinalIgnoreCase);
            var route = EscapeStringLiteral(ep.Route);

            sb.Append("        /// <summary>").Append(ep.Method?.ToUpperInvariant() ?? "POST")
                .Append(" RunScript/").Append(ep.Route).AppendLine(" — generated from the schema manifest.</summary>");

            if (requestType == null)
            {
                // No request shape: parameterless call.
                sb.Append("        public static Task<global::Lelware.Sdk.LelwareResult<").Append(responseType).Append(">> ").Append(ep.Name)
                    .AppendLine("Async(this global::Lelware.Sdk.LelwareClient client, CancellationToken ct = default)");
                if (isGet)
                {
                    sb.Append("            => client.GetScriptAsync<").Append(responseType)
                        .Append(">(\"").Append(route).AppendLine("\", null, ct);");
                }
                else
                {
                    sb.Append("            => client.CallScriptAsync<object, ").Append(responseType)
                        .Append(">(\"").Append(route).AppendLine("\", null, ct);");
                }

                sb.AppendLine();
                return;
            }

            sb.Append("        public static Task<global::Lelware.Sdk.LelwareResult<").Append(responseType).Append(">> ").Append(ep.Name)
                .Append("Async(this global::Lelware.Sdk.LelwareClient client, ").Append(requestType)
                .AppendLine(" request, CancellationToken ct = default)");

            if (isGet)
            {
                // GET: turn the request's fields into a query-string dictionary.
                sb.AppendLine("        {");
                sb.AppendLine("            var query = new Dictionary<string, string>();");
                if (ep.Request?.Fields != null)
                {
                    foreach (var f in ep.Request.Fields)
                    {
                        var wire = string.IsNullOrEmpty(f.Json) ? f.Name : f.Json;
                        sb.Append("            query[\"").Append(EscapeStringLiteral(wire))
                            .Append("\"] = global::System.Convert.ToString(request.").Append(f.Name)
                            .AppendLine(", global::System.Globalization.CultureInfo.InvariantCulture);");
                    }
                }

                sb.Append("            return client.GetScriptAsync<").Append(responseType)
                    .Append(">(\"").Append(route).AppendLine("\", query, ct);");
                sb.AppendLine("        }");
            }
            else
            {
                sb.Append("            => client.CallScriptAsync<").Append(requestType).Append(", ").Append(responseType)
                    .Append(">(\"").Append(route).AppendLine("\", request, ct);");
            }

            sb.AppendLine();
        }

        // Resolve a request/response shape to a concrete C# type name. An explicit `type`
        // wins; otherwise, if fields were declared, the generated `{name}` class is used;
        // otherwise the fallback (null = "no type", object = untyped).
        private static string ResolveType(ShapeDef shape, string generatedName, string fallback)
        {
            if (shape != null && !string.IsNullOrEmpty(shape.Type))
            {
                return shape.Type;
            }

            if (shape?.Fields != null && shape.Fields.Count > 0)
            {
                return generatedName;
            }

            return fallback;
        }

        private static string EscapeStringLiteral(string value)
        {
            return (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
